### ISSUE TITLE
New tag/release

### ISSUE THREAD

**Issue by phls** [marekjm/clap#4]
Hi, I intend to package your software because it's a dependency to another software. I saw you did a commit last year.

Could you make a new tag/release? I will use it to package.

Thanks,

**Comment by marekjm** [comment]
Sure. Here is a new `v0.14.0` tag: https://github.com/marekjm/clap/tree/v0.14.0

If this is sufficient for you, please close the issue. Happy hacking and thanks for reaching out! May I know what software you had in mind?

**Comment by phls** [comment]
Hi, thanks.

This software: diacli

**Comment by phls** [comment]
Hi @marekjm 

There is a LICENSE file as GPL-3+, but README.markdown says "GPL-3+ or LGPL-3+".

And in setup.py quoted MIT.

Could you clarify me what is the correct?

Thanks.

**Comment by marekjm** [comment]
Hi.

CLAP is published under GNU GPL v3 or later, or under LGPL v3 or later. I don't know the lawyer-speak for this, but the intention is for the code to be available under either GPL or LGPL. The code is not published under MIT, so `setup.py` is incorrect.

**Comment by phls** [comment]
Thanks.
